### ISSUE TITLE
Conection to DALL.E fails

### ISSUE THREAD

**Issue by chauhanarya007** [adrianhajdin/project_threejs_ai#14]
I get this error whenever I try to prompt the dalle prompt from client side:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
can anyone help?

**Comment by quikdave** [comment]
I'm getting same, seems to be CORS causing it. Investigating.

**Comment by Preyash-tryin-to-code** [comment]
Did you find any fix for it?
@chauhanarya007

**Comment by quikdave** [comment]
Hi guys,

I found that the openAI key in the .env variable is not been accepted in the dalle.route.js. As a work around I manually updated the dalle.routes.js with the the key

const config = new Configuration({
  apiKey: **process.env.OPENAI_API_KEY**,
});

const config = new Configuration({
  apiKey: **ACTUAL OPENAI KEY,**
});

This got the project to start accepting AI commands from the chat section. I'm still investigating why this variable is not been parsed but it gets the project working so you can move on.

**Comment by chauhanarya007** [comment]
Guys I figured out the problem, you need to check on the open ai platform if you have free credits or not, for me all were used so I had to pay for them and it started working fine. Hope it helps
