### ISSUE TITLE
T-shirt color not changing

### ISSUE THREAD

**Issue by fsalasc** [adrianhajdin/project_threejs_ai#15]
Hi, 

Is anyone else facing the same problem? 
I've followed all the steps but no luck, also I downloaded the repo and after running it it seems like the issue is present here too.
I don't know why when selecting the color from the color picker the shirt does not change, said that, the initial color is not applied too.

Thanks in advance for any help ✋ 

![image](https://github.com/adrianhajdin/project_threejs_ai/assets/122741932/a4193532-2f40-4033-a828-14667b0e9a86)

**Comment by SergDeved** [comment]
Let's try to dissable cache or change to private navigation or another browser, the DALLE API is working for you?

**Comment by pradeepth02** [comment]
As soon as i click on ai full or ai logo button my screen goes white and i can see errors on the server terminal and even in inspect console.
![Screenshot (8)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/3f35cfde-1f1a-4d50-9e24-91f7f745ab1e)
![Screenshot (9)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/712d6f9b-014d-4565-a1fd
![Screenshot (10)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/ce78e289-260d-481d-b3f4-38cfe98ab756)
-8d91beeafb68)
![Screenshot (11)](https://github.com/adrianhajdin/project_threejs_ai/assets/115602871/e8dba14d-2033-4c15-85ae-04699646b1ea)
Can someone please help me out with this....?

**Comment by fsalasc** [comment]
Solved by @r4dhwene in here: https://github.com/adrianhajdin/project_threejs_ai/issues/22
