### ISSUE TITLE
Anyone having the same issue? How to resolve it>

### ISSUE THREAD

**Issue by Jyotishmoy12** [adrianhajdin/project_threejs_ai#24]
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
index-255a5e79.js:3455     GET https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/hdris/potsdamer-platz/potsdamer_platz_1k.hdr net::ERR_SSL_UNRECOGNIZED_NAME_ALERT
load @ index-255a5e79.js:3455
load @ index-255a5e79.js:3455
load @ index-255a5e79.js:3580
(anonymous) @ index-255a5e79.js:3489
(anonymous) @ index-255a5e79.js:3489
(anonymous) @ index-255a5e79.js:3489
jF @ index-255a5e79.js:3489
C7 @ index-255a5e79.js:3489
Eo @ index-255a5e79.js:3489
QO @ index-255a5e79.js:3581
YO @ index-255a5e79.js:3581
Ly @ index-255a5e79.js:3483
tE @ index-255a5e79.js:3485
YC @ index-255a5e79.js:3485
FU @ index-255a5e79.js:3485
Am @ index-255a5e79.js:3485
JC @ index-255a5e79.js:3485
C @ index-255a5e79.js:3471
V @ index-255a5e79.js:3471
index-255a5e79.js:3485 Error: Could not load potsdamer-platz/potsdamer_platz_1k.hdr: Failed to fetch)
    at Object.onError (index-255a5e79.js:3489:23065)
    at index-255a5e79.js:3455:185159
Ny @ index-255a5e79.js:3485
P.componentDidCatch.y.callback @ index-255a5e79.js:3485
Ob @ index-255a5e79.js:3483
HC @ index-255a5e79.js:3485
zC @ index-255a5e79.js:3485
LU @ index-255a5e79.js:3485
kU @ index-255a5e79.js:3485
Va @ index-255a5e79.js:3485
JC @ index-255a5e79.js:3485
C @ index-255a5e79.js:3471
V @ index-255a5e79.js:3471
index-255a5e79.js:40 Error: Could not load potsdamer-platz/potsdamer_platz_1k.hdr: Failed to fetch)
    at Object.onError (index-255a5e79.js:3489:23065)
    at index-255a5e79.js:3455:185159
D_ @ index-255a5e79.js:40
t.callback @ index-255a5e79.js:40
jE @ index-255a5e79.js:38
lT @ index-255a5e79.js:40
LI @ index-255a5e79.js:40
i5 @ index-255a5e79.js:40
u5 @ index-255a5e79.js:40
rl @ index-255a5e79.js:40
II @ index-255a5e79.js:40
C @ index-255a5e79.js:25
V @ index-255a5e79.js:25
index-255a5e79.js:3489 Uncaught Error: Could not load potsdamer-platz/potsdamer_platz_1k.hdr: Failed to fetch)
    at Object.onError (index-255a5e79.js:3489:23065)
    at index-255a5e79.js:3455:185159
(anonymous) @ index-255a5e79.js:3489
(anonymous) @ index-255a5e79.js:3455
index-255a5e79.js:3455 THREE.WebGLRenderer: Context Lost.

**Comment by Jyotishmoy12** [comment]
Resolved

**Comment by ayushx007** [comment]
> Resolved

How did you fix this issue?
