### ISSUE TITLE
Does anyone get the same error?

### ISSUE THREAD

**Issue by Jyotishmoy12** [adrianhajdin/project_threejs_ai#3]
POST http://localhost:8080/api/v1/dalle 500 (Internal Server Error)
handleSubmit @ Customizer.jsx:56
handleClick @ AIPicker.jsx:27
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
data:image/png;base64,undefined:1          GET data:image/png;base64,undefined net::ERR_INVALID_URL
Image (async)
load @ three.module.js:41632
load @ three.module.js:41813
(anonymous) @ index-bb759d07.esm.js:1621
(anonymous) @ index-bb759d07.esm.js:1621
(anonymous) @ index-bb759d07.esm.js:1621
query @ index.js:34
suspend @ index.js:53
useLoader @ index-bb759d07.esm.js:1637
useTexture @ useTexture.js:8
Shirt @ Shirt.jsx:13
renderWithHooks @ react-reconciler.development.js:7363
updateFunctionComponent @ react-reconciler.development.js:11802
beginWork @ react-reconciler.development.js:13845
beginWork$1 @ react-reconciler.development.js:19513
performUnitOfWork @ react-reconciler.development.js:18686
workLoopSync @ react-reconciler.development.js:18597
renderRootSync @ react-reconciler.development.js:18565
performSyncWorkOnRoot @ react-reconciler.development.js:18183
flushSyncCallbacks @ react-reconciler.development.js:2936
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
2index-bb759d07.esm.js:1624 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-bb759d07.esm.js:1624:36
    at HTMLImageElement.onImageError (three.module.js:41607:19)
(anonymous) @ index-bb759d07.esm.js:1624
onImageError @ three.module.js:41607
VM2174:1 The above error occurred in the <Shirt> component:

    at Shirt (http://127.0.0.1:5173/src/canvas/Shirt.jsx:25:16)
    at group
    at group
    at group
    at Center2 (http://127.0.0.1:5173/node_modules/.vite/deps/@react-three_drei.js?v=f2e54866:97457:3)
    at group
    at CameraRig (http://127.0.0.1:5173/src/canvas/CameraRig.jsx:23:3)
    at Suspense
    at ErrorBoundary (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-XFAQTPWW.js?v=f2e54866:16132:5)
    at FiberProvider (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-XFAQTPWW.js?v=f2e54866:17860:21)
    at Provider (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-XFAQTPWW.js?v=f2e54866:17462:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
eval @ VM2174:1
logCapturedError @ react-reconciler.development.js:9747
callback @ react-reconciler.development.js:9815
callCallback @ react-reconciler.development.js:4279
commitUpdateQueue @ react-reconciler.development.js:4300
commitLayoutEffectOnFiber @ react-reconciler.development.js:14877
commitLayoutMountEffects_complete @ react-reconciler.development.js:16290
commitLayoutEffects_begin @ react-reconciler.development.js:16276
commitLayoutEffects @ react-reconciler.development.js:16214
commitRootImpl @ react-reconciler.development.js:18945
commitRoot @ react-reconciler.development.js:18811
finishConcurrentRender @ react-reconciler.development.js:17990
performConcurrentWorkOnRoot @ react-reconciler.development.js:17907
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
2index-bb759d07.esm.js:1624 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-bb759d07.esm.js:1624:36
    at HTMLImageElement.onImageError (three.module.js:41607:19)
(anonymous) @ index-bb759d07.esm.js:1624
onImageError @ three.module.js:41607
VM2174:1 The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-XFAQTPWW.js?v=f2e54866:18002:3)
    at FiberProvider (http://127.0.0.1:5173/node_modules/.vite/deps/chunk-XFAQTPWW.js?v=f2e54866:17860:21)
    at CanvasWrapper
    at CanvasModel
    at main
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
eval @ VM2174:1
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:26923 Uncaught Error: Could not load data:image/png;base64,undefined: undefined)
    at index-bb759d07.esm.js:1624:36
    at HTMLImageElement.onImageError (three.module.js:41607:19)
(anonymous) @ index-bb759d07.esm.js:1624
onImageError @ three.module.js:41607
three.module.js:28071 THREE.WebGLRenderer: Context Lost.

**Comment by krishnanjalivu** [comment]
Yes,Even iam experiencing same issues

**Comment by gyanaranjans** [comment]
I got the same  issue too

**Comment by Jyotishmoy12** [comment]
> Yes, I'm experiencing the same issue and I think the server hosting the image is down or experiencing issues.

Hey if you find the solution plss plsss tell meee... i would do the same... :D

**Comment by Jyotishmoy12** [comment]
> Yes, I'm experiencing the same issue and I think the server hosting the image is down or experiencing issues.

Hey if you find the solution plssss plsss tell meeee.. I would do the sameeeee.....

**Comment by Jyotishmoy12** [comment]
> Yes,Even iam experiencing same issues
Hey if you find the solution plssss plsss tell meeee.. I would do the sameeeee.....

**Comment by Jyotishmoy12** [comment]
> I got the same issue too

Hey if you find the solution plssss plsss tell meeee.. I would do the sameeeee.....

**Comment by N0t-Sur3** [comment]
same

**Comment by Jyotishmoy12** [comment]
Hey everyone I have found the solution we just need to create a new account becoz open ai some kind of credit thing if you use multiple api keys the credit ends hence the api won't work...hope this helps..

**Comment by bArryAllen6843** [comment]
> Hey everyone I have found the solution we just need to create a new account becoz open ai has some kind of credit thing if you use multiple api keys the credit ends hence the api won't work...hope this helps..

I have only made a single api key but still not getting results, I think api key only works with paid open ai

**Comment by gyanaranjans** [comment]
> Hey everyone I have found the solution we just need to create a new account becoz open ai has some kind of credit thing if you use multiple api keys the credit ends hence the api won't work...hope this helps..

Thats not the solution

**Comment by mnosov622** [comment]
For me it was because I have used all my free credits, so it seems to giving 500 for that reason.

**Comment by outerspacesoph** [comment]
im getting the same error and I haven't used any api keys before so I shouldn't be out of credits?
