### ISSUE TITLE
I am getting an  undefined (reading '0') error. Any solution for this?

### ISSUE THREAD

**Issue by tanbiralam** [adrianhajdin/project_threejs_ai#49]
This is the customiser.jsx file

import React, { useState, useEffect } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useSnapshot } from "valtio";

import config from "../config/config";
import state from "../store";
import { download } from "../assets";
import { downloadCanvasToImage, reader } from "../config/helpers";
import { EditorTabs, FilterTabs, DecalTypes } from "../config/constants";
import { fadeAnimation, slideAnimation } from "../config/motion";
import {
  AIPicker,
  ColorPicker,
  CustomButton,
  FilePicker,
  Tab,
} from "../components";

const Customiser = () => {
  const snap = useSnapshot(state);

  const [file, setFile] = useState("");

  const [prompt, setPrompt] = useState("");
  const [generatingImg, setGeneratingImg] = useState(false);

  const [activeEditorTab, setActiveEditorTab] = useState("");
  const [activeFilterTab, setActiveFilterTab] = useState({
    logoShirt: true,
    stylishShirt: false,
  });

  // show tab content depending on the activeTab
  const generateTabContent = () => {
    switch (activeEditorTab) {
      case "colorpicker":
        return <ColorPicker />;
      case "filepicker":
        return <FilePicker file={file} setFile={setFile} readFile={readFile} />;
      case "aipicker":
        return (
          <AIPicker
            prompt={prompt}
            setPrompt={setPrompt}
            generatingImg={generatingImg}
            handleSubmit={handleSubmit}
          />
        );
      default:
        return null;
    }
  };

  const handleSubmit = async (type) => {
    if (!prompt) return alert("Please enter a prompt");

    try {
      setGeneratingImg(true);

      const response = await fetch("http://localhost:8080/api/v1/dalle", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt,
        }),
      });

      if (!response.ok) {
        // Handle non-successful HTTP response (e.g., 404, 500, etc.)
        throw new Error(`HTTP Error: ${response.status}`);
      }

      const data = await response.json();

      handleDecals(type, `data:image/png;base64,${data.image}`);
    } catch (error) {
      alert(error);
    } finally {
      setGeneratingImg(false);
      setActiveEditorTab("");
    }
  };

  

  const handleDecals = (type, result) => {
    const decalType = DecalTypes[type];

    state[decalType.stateProperty] = result;

    if (!activeFilterTab[decalType.filterTab]) {
      handleActiveFilterTab(decalType.filterTab);
    }
  };

  const handleActiveFilterTab = (tabName) => {
    switch (tabName) {
      case "logoShirt":
        state.isLogoTexture = !activeFilterTab[tabName];
        break;
      case "stylishShirt":
        state.isFullTexture = !activeFilterTab[tabName];
        break;
      default:
        state.isLogoTexture = true;
        state.isFullTexture = false;
        break;
    }

    // after setting the state, activeFilterTab is updated

    setActiveFilterTab((prevState) => {
      return {
        ...prevState,
        [tabName]: !prevState[tabName],
      };
    });
  };

  const readFile = (type) => {
    reader(file).then((result) => {
      handleDecals(type, result);
      setActiveEditorTab("");
    });
  };

  return (
    <AnimatePresence>
      {!snap.intro && (
        <>
          <motion.div
            key="custom"
            className="absolute top-0 left-0 z-10"
            {...slideAnimation("left")}
          >
            <div className="flex items-center min-h-screen">
              <div className="editortabs-container tabs">
                {EditorTabs.map((tab) => (
                  <Tab
                    key={tab.name}
                    tab={tab}
                    handleClick={() => setActiveEditorTab(tab.name)}
                  />
                ))}

                {generateTabContent()}
              </div>
            </div>
          </motion.div>

          <motion.div
            className="absolute z-10 top-5 right-5"
            {...fadeAnimation}
          >
            <CustomButton
              type="filled"
              title="Go Back"
              handleClick={() => (state.intro = true)}
              customStyles="w-fit px-4 py-2.5 font-bold text-sm"
            />
          </motion.div>

          <motion.div
            className="filtertabs-container"
            {...slideAnimation("up")}
          >
            {FilterTabs.map((tab) => (
              <Tab
                key={tab.name}
                tab={tab}
                isFilterTab
                isActiveTab={activeFilterTab[tab.name]}
                handleClick={() => handleActiveFilterTab(tab.name)}
              />
            ))}

            <button className="download-btn" onClick={downloadCanvasToImage}>
              <img
                src={download}
                alt="download_image"
                className="w-3/5 h-3/5 object-contain"
              />
            </button>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};

export default Customiser;

This is the dalle-routes.js file- 
import express from 'express';
import * as dotenv from 'dotenv';
import  OpenAIApi from 'openai';

dotenv.config();

const router = express.Router();

const openai = new OpenAIApi({
    apiKey: process.env.OPEN_AI_API_KEY,
  });;

router.route('/').get((req, res) => {
  res.status(200).json({ message: "Hello from DALL.E ROUTES" })
})

router.route('/').post(async (req, res) => {
  try {
    const { prompt } = req.body;

    const response = await openai.images.generate({
      prompt: prompt,
      n: 1,
      size: '1024x1024',
      response_format: 'b64_json'
    });

    const image = response.data.data[0].b64_json;

    res.status(200).json({ photo: image });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Something went badly" })
  }
})

export default router;

how to fix this issue

**Comment by tanbiralam** [comment]
Now i am getting this kind of error. 
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/57638199/d8973a7a-d632-4d8e-a86f-4874af5d44d9)
 Also this is

**Comment by tanbiralam** [comment]
Now i am getting this kind of issue: 
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/57638199/197ffa0b-9cf6-4cca-bc03-6257d65c2969)
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/57638199/ec02ee1f-4b36-4bd5-a25a-634354f3540e)

**Comment by tanbiralam** [comment]
I am getting this error: 
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/57638199/dd5a1777-1f6a-4269-9993-7cf8061c4128)
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/57638199/61765505-1787-433c-ac0a-2fca728c832e)

**Comment by Alimzade** [comment]
import statement for OpenAI should be `import OpenAI from 'openai';`  not `import OpenAIApi from 'openai';`
Also try updating your packages using `npm update` in root directory.  

If that does not work, please provide your latest code for dalle.routes.js and const handleSubmit from Customizer.jsx

**Comment by tanbiralam** [comment]
Thanks, I have solved the issue.  i have change the openai.createImage to openai.images.generate and also modifies the get reqeust.
`const openaiResponse = await openai.createImage({
      prompt,
      n: 1,
      size: '1024x1024',
      response_format: 'b64_json'
    });`

**Comment by Alimzade** [comment]
@tanbiralam I am happy to hear that you figured it out. Well done! 

You can close this issue now. Good luck with your website.

**Comment by tanbiralam** [comment]
yeah, man.
