### ISSUE TITLE
Even after removing the Environement line, rotation error coming and shirt model is also not rendering

### ISSUE THREAD

**Issue by ImDoubD** [adrianhajdin/project_threejs_ai#51]
![image](https://github.com/adrianhajdin/project_threejs_ai/assets/129399840/ab99140b-c180-4cae-8378-acaa38b1fb0e)

Can somebody help me solve it,
ping me on discord if possible, 
just join here : https://discord.gg/W2mbmRQa

**Comment by kapilsinghnegi** [comment]
I am also facing this same issue, need help.

**Comment by ImDoubD** [comment]
figured it out.

**Comment by kapilsinghnegi** [comment]
tell below

**Comment by ImDoubD** [comment]
Initialise the const group. Since its only been declared so it is not able to get rotation as an attribute, hence the error.
________________________________
