### ISSUE TITLE
shirt-baked.glb

### ISSUE THREAD

**Issue by piyushbaibhav** [adrianhajdin/project_threejs_ai#54]
![Screenshot 2023-11-04 062916](https://github.com/adrianhajdin/project_threejs_ai/assets/98445212/452282ae-949a-46ee-8686-47e8a88ebf45)
![Screenshot 2023-11-04 062900](https://github.com/adrianhajdin/project_threejs_ai/assets/98445212/8b6e659b-2fd3-4ff9-8cb0-2cf703601981)
I am not able to solve this. please somone help me.

**Comment by dinobronx** [comment]
@piyushbaibhav your public folder has an extra public folder inside. Try adding the given public folder again under the client folder and make sure you replace the existing public folder.

**Comment by piyushbaibhav** [comment]
@dinobronx thanks a lot. I guess it worked but I can't see it cuz of the canvas I guess. everything became black.
![Screenshot 2023-11-19 040709](https://github.com/adrianhajdin/project_threejs_ai/assets/98445212/dc247a3e-2c9a-4946-8a89-c7840681464f)
