### ISSUE TITLE
Error : Could not load data:image/png;base64,undefined: undefined

### ISSUE THREAD

**Issue by Shaheer5** [adrianhajdin/project_threejs_ai#67]
## Problem
I think I have not properly migrated to OpenAI v4,
I could use some help make it work.

the errors I'm getting are:
- POST http://localhost:8080/api/v1/dalle 500 (Internal Server Error)
- Error: Could not load data:image/png;base64,undefined: undefined
    at chunk-NSXAVJG4.js?v=007676ee:17070:39
    at HTMLImageElement.onImageError (chunk-7Z2GYTU5.js?v=007676ee:26069:20)

## Code
`// this is created using v4 of OpenAI API

import express from "express";
import * as dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config();

const router = express.Router();

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

router.route("/").get((req, res) => {
  res.status(200).json({ message: "Hello from DALL-E routes" });
});

// posting image to front-end app
router.route("/").post(async (req, res) => {
  try {
    const { prompt } = req.body;
    const aiResponse = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      n: 1,
      size: "1024x1024",
      response_format: "b64_json",
    });
    const image = aiResponse.data.data[0].b64_json;
    res.status(200).json({ photo: image });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Something went wrong" });
  }
});

export default router;
`

**Comment by Mohamed-Ismail-Dev** [comment]
Have you solved the error?
if yes, Help me i got the same error . I changed my code to the above given but it don't work

**Comment by Shaheer5** [comment]
Not working for me as well. It say open ai budget limit exceeded. even on a fresh account free trail

**Comment by ritik-t** [comment]
Fix: The issue is how you extract the image from the response body.
In your dalle.routes.js
Change this line -> const image = aiResponse.data.data[0].b64_json;
To this line -> const image = aiResponse.data[0].b64_json;

**Comment by ritik-t** [comment]
> Not working for me as well. It say open ai budget limit exceeded. even on a fresh account free trail

Also, you will have to add balance to your openAI account, because openAI has stopped giving free credit to new accounts.
